version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    ports:
      - '3000:3000'
      - '3001:3001'
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    # Run "bun mikro db:create" to create the database then uncomment the line below
    volumes:
    - ./comfyui.manager.db:/usr/src/app/comfyui.manager.db
