version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        - NEXT_PUBLIC_APP_URL=http://localhost:3000
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - BACKEND_URL_INTERNAL=http://server:3001
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - NODE_ENV=production
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - comfy_network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '3001:3001'
    env_file:
      - .env
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
    networks:
      - comfy_network

networks:
  comfy_network:
    driver: bridge
