version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server
    networks:
      - comfy_network

  app:
    build:
      context: .
      dockerfile: webapp.dockerfile
      args:
        - NEXT_PUBLIC_APP_URL=http://localhost:3000
    env_file:
      - .env
    environment:
      - BE_SAME_DOMAIN=true
      - BACKEND_URL_INTERNAL=http://server:3001
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - NODE_ENV=production
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - comfy_network
    expose:
      - '3000'

  server:
    build:
      context: .
      dockerfile: server.dockerfile
    env_file:
      - .env
    environment:
      - BE_SAME_DOMAIN=true
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
    networks:
      - comfy_network
    expose:
      - '3001'

networks:
  comfy_network:
    driver: bridge
