name: Push docker hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'release-please') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push webapp image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: webapp.dockerfile
          push: true
          tags: tctien342/comfy-station-webapp:latest

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: server.dockerfile
          push: true
          tags: tctien342/comfy-station-backend:latest
